name: commands on GithubActions 
on:  
  workflow_dispatch: 
jobs:
  exmaple:
    runs-on: ubuntu-latest
    steps:
      # - run: | 
      #     deprecated=true 
      #     if [[ deprecated ]]; then 
      #       echo " ::warning::Deprecated function found"
      #     fi 
      - name: Set API Key 
        run: echo "API_KEY=12345" >> $GITHUB_ENV 
      - name: Use API KEY 
        run: "echo $API_KEY "
