# Workflow to learn how to implement multiple jobs in sequence and with dependencies
name: Multi-Job Workflow

on:
  workflow_dispatch: # allows manual trigger

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Create project
        run: |
          mkdir -p temp
          cd temp
          npm init -y

      - name: Add build script
        run: npm pkg set scripts.build="echo Building project..."
        working-directory: ./temp

      - name: Install dependencies
        run: npm install
        working-directory: ./temp

      - name: Run build
        run: npm run build
        working-directory: ./temp
