# Workflow to learn how to implement multiple jobs in sequence and with dependencies
name: Multi-Job Workflow

on:
  workflow_dispatch: # allows manual trigger

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print job name
        run:  "echo Job: ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1 # starts after job_1
    steps:
      - name: Print job name
        run:   "echo Job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_2 # starts after job_2
    steps:
      - name: Print job name
        run:  "echo Job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: 
      - job_2
      - job_3 # starts after both job_2 and job_3 complete
    steps:
      - name: Print job name
        run:  "echo Job: ${{ github.job }}"
