# Workflow to learn how to implement multiple jobs in sequence and with dependencies
name: Multi-Job Workflow

on:
  workflow_dispatch: # allows manual trigger

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install 
          npm run build 
        working-directory: ./temp
        shell: bash # pwsh , cmd , powershell , python 
      - run: print %ENV
        shell: perl {0}
        
