# Workflow to learn how to implement multiple jobs in sequence and with dependencies
name: Multi-Job Workflow

on:
  workflow_dispatch: # allows manual trigger

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: adds the temp directory 
        run: mkdir -p ./temp
      - name: List files 
        run: ls -la 
      - name: Install and build project
        run: |
          npm install
          npm run build
        working-directory: ./temp
        shell: bash

      - name: Print environment variables using Perl
        run: print %ENV
        shell: perl {0}
