name: Manual workflow 
on: 
  workflow_dispatch: 
    inputs:
      environment: 
        description: "Choose environment"
        required: true 
        default:  "staging"
        type: choice 
        options:
          -  staging 
          -  testing 
          -  developing 
          -  production 
          
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy-app
        run: echo "deploying the applications ${{ inputs.environment }}"
