on:
  schedule:
    - cron: "0 22 * * *" 
    - cron: "5 2 * * *" 
    - cron: "1 * * * *"


jobs: 
  daily-task: 
    runs-on: ubuntu-latest 
    steps:
      - name: Print message 
        run: echo "running the scheduled task"
